"""Initial pipeline tables.

Revision ID: 6795fdb37410
Revises:
Create Date: 2025-11-04 11:22:49.548712

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6795fdb37410'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create pgvector extension first
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: 'fermi' table is created as a materialized view at the end, not here
    op.create_table(
        'seeds',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('seed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            'embedding',
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            nullable=True,
        ),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_seeds_seed'), 'seeds', ['seed'], unique=True)
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('locale', sa.Enum('US', 'EU', name='locale'), nullable=False),
        sa.Column('login_streak', sa.Integer(), nullable=False),
        sa.Column('last_login_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firebase_uid'), 'user', ['firebase_uid'], unique=True)
    # Note: No FK constraint to fermi.uid since fermi is a materialized view
    # and PostgreSQL doesn't support FKs to materialized views
    op.create_table(
        'answer_events',
        sa.Column('uid', sa.Uuid(), nullable=False),
        sa.Column('question_uid', sa.Uuid(), nullable=False),
        sa.Column(
            'question_difficulty',
            sa.Enum('EASY', 'MEDIUM', 'HARD', name='questiondifficulty'),
            nullable=False,
        ),
        sa.Column(
            'question_category',
            sa.Enum(
                'PLANET_EARTH',
                'HUMANITY_BY_NUMBERS',
                'POP_CULTURE',
                'SHOWER_THOUGHTS',
                'COSMIC_PERSPECTIVE',
                'OTHER',
                name='questioncategory',
            ),
            nullable=False,
        ),
        sa.Column(
            'user_firebase_id',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('answer', sa.JSON(), nullable=True),
        sa.Column('correct_answer', sa.JSON(), nullable=True),
        sa.Column('score_number', sa.Float(), nullable=False),
        sa.Column('score_quantile', sa.Float(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('uid'),
    )
    op.create_index(
        op.f('ix_answer_events_user_firebase_id'),
        'answer_events',
        ['user_firebase_id'],
        unique=False,
    )
    op.create_table(
        'fermi_questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('seed_id', sa.Integer(), nullable=True),
        sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            'embedding',
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            nullable=True,
        ),
        sa.Column('source', sa.JSON(), nullable=True),
        sa.Column(
            'category',
            sa.Enum(
                'PLANET_EARTH',
                'HUMANITY_BY_NUMBERS',
                'POP_CULTURE',
                'SHOWER_THOUGHTS',
                'COSMIC_PERSPECTIVE',
                'OTHER',
                name='questioncategory',
            ),
            nullable=True,
        ),
        sa.Column(
            'difficulty',
            sa.Enum('EASY', 'MEDIUM', 'HARD', name='questiondifficulty'),
            nullable=True,
        ),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ['seed_id'],
            ['seeds.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_fermi_questions_seed_id'),
        'fermi_questions',
        ['seed_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_fermi_questions_category'),
        'fermi_questions',
        ['category'],
        unique=False,
    )
    # Note: No FK constraint to fermi.uid since fermi is a materialized view
    # and PostgreSQL doesn't support FKs to materialized views
    op.create_table(
        'questions_votes',
        sa.Column('question_uid', sa.Uuid(), nullable=False),
        sa.Column(
            'user_firebase_uid',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column('verdict', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('question_uid', 'user_firebase_uid'),
    )
    op.create_table(
        'seeds_usage',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('seed_id', sa.Integer(), nullable=False),
        sa.Column('requested', sa.Integer(), nullable=False),
        sa.Column('generated', sa.Integer(), nullable=False),
        sa.Column('yielded', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ['seed_id'],
            ['seeds.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_seeds_usage_created_at'),
        'seeds_usage',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_seeds_usage_seed_id'),
        'seeds_usage',
        ['seed_id'],
        unique=False,
    )
    # Note: No FK constraint to fermi.uid since fermi is a materialized view
    # and PostgreSQL doesn't support FKs to materialized views
    op.create_table(
        'user_question_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('question_uid', sa.Uuid(), nullable=False),
        sa.Column('seen_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_user_question_history_question_uid'),
        'user_question_history',
        ['question_uid'],
        unique=False,
    )
    op.create_index(
        op.f('ix_user_question_history_user_id'),
        'user_question_history',
        ['user_id'],
        unique=False,
    )
    op.create_table(
        'fermi_answers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('number', sa.Float(), nullable=False),
        sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('used_ai_overview', sa.Boolean(), nullable=False),
        sa.Column('success', sa.Boolean(), nullable=False),
        sa.Column('serp_metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ['question_id'],
            ['fermi_questions.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_fermi_answers_question_id'),
        'fermi_answers',
        ['question_id'],
        unique=True,
    )
    op.create_table(
        'raw_questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('seed_id', sa.Integer(), nullable=True),
        sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            'embedding',
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            nullable=True,
        ),
        sa.Column('source', sa.JSON(), nullable=True),
        sa.Column('dedup_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('canonical_question_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ['canonical_question_id'],
            ['fermi_questions.id'],
        ),
        sa.ForeignKeyConstraint(
            ['seed_id'],
            ['seeds.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_raw_questions_seed_id'),
        'raw_questions',
        ['seed_id'],
        unique=False,
    )
    # ### end Alembic commands ###

    # Create uuid-ossp extension for uuid_generate_v5
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # Manually create materialized view 'fermi' (autogenerate treats it as a table)
    # Use uuid_generate_v5 to create deterministic UUIDs based on question_id
    # This ensures UIDs remain stable across materialized view refreshes
    op.execute(
        """
        CREATE MATERIALIZED VIEW fermi AS
        SELECT
            uuid_generate_v5(
                '6ba7b810-9dad-11d1-80b4-00c04fd430c8'::uuid,
                fq.id::text
            ) AS uid,
            fq.id AS question_id,
            fq.text,
            fq.source AS question_source,
            fa.id AS answer_id,
            fa.number,
            fa.unit,
            fa.snippet,
            fa.used_ai_overview,
            fq.difficulty,
            fq.category,
            floor(random() * 2147483647)::int AS random_sort_key,
            fq.created_at,
            fa.created_at AS updated_at
        FROM fermi_answers fa
        INNER JOIN fermi_questions fq ON fa.question_id = fq.id
        WHERE fa.success = true
        """,
    )
    # Create indexes on materialized view
    op.execute(
        """
        CREATE UNIQUE INDEX ix_fermi_uid ON fermi (uid)
        """,
    )
    op.execute(
        """
        CREATE INDEX ix_fermi_random_sort_key ON fermi (random_sort_key)
        """,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop materialized view first (CASCADE removes dependent objects)
    op.execute('DROP MATERIALIZED VIEW IF EXISTS fermi CASCADE')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_questions_seed_id'), table_name='raw_questions')
    op.drop_table('raw_questions')
    op.drop_index(op.f('ix_fermi_answers_question_id'), table_name='fermi_answers')
    op.drop_table('fermi_answers')
    op.drop_index(
        op.f('ix_user_question_history_user_id'),
        table_name='user_question_history',
    )
    op.drop_index(
        op.f('ix_user_question_history_question_uid'),
        table_name='user_question_history',
    )
    op.drop_table('user_question_history')
    op.drop_index(op.f('ix_seeds_usage_seed_id'), table_name='seeds_usage')
    op.drop_index(op.f('ix_seeds_usage_created_at'), table_name='seeds_usage')
    op.drop_table('seeds_usage')
    op.drop_table('questions_votes')
    op.drop_index(op.f('ix_fermi_questions_category'), table_name='fermi_questions')
    op.drop_index(op.f('ix_fermi_questions_seed_id'), table_name='fermi_questions')
    op.drop_table('fermi_questions')
    op.drop_index(op.f('ix_answer_events_user_firebase_id'), table_name='answer_events')
    op.drop_table('answer_events')
    op.drop_index(op.f('ix_user_firebase_uid'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_seeds_seed'), table_name='seeds')
    op.drop_table('seeds')
    # ### end Alembic commands ###

    # Drop extensions
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp"')
    op.execute('DROP EXTENSION IF EXISTS vector')
