"""Prompts for the Fermi core."""

from .prompts import (
    ASK_PROMPT,
    CATEGORIZE_PROMPT,
    DIFFICULTY_PROMPT,
    EXTRACT_INFO_PROMPT,
    LLM_ANSWER_PROMPT,
    SELECT_LOCATION_PROMPT,
)

__all__ = [
    'ASK_PROMPT',
    'CATEGORIZE_PROMPT',
    'DIFFICULTY_PROMPT',
    'EXTRACT_INFO_PROMPT',
    'LLM_ANSWER_PROMPT',
    'SELECT_LOCATION_PROMPT',
]
