// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTxXAA5eNP0n9vUFn5zoUzSsyCRGj8nZI',
    appId: '1:811437731406:android:0bd8e579fb90608e3c1d1f',
    messagingSenderId: '811437731406',
    projectId: 'guesstimate-dev-478820',
    storageBucket: 'guesstimate-dev-478820.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD755WUMnXJcqZQkliW1R0mNh4RlofnfqE',
    appId: '1:811437731406:web:28ac71a4e2783ef83c1d1f',
    messagingSenderId: '811437731406',
    projectId: 'guesstimate-dev-478820',
    authDomain: 'guesstimate-dev-478820.firebaseapp.com',
    storageBucket: 'guesstimate-dev-478820.firebasestorage.app',
    measurementId: 'G-56D6HMHBHS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEuwflWzwOzaGeDUgtLfrptKD6uDJgRqA',
    appId: '1:811437731406:ios:0c2eb1e88943ec3e3c1d1f',
    messagingSenderId: '811437731406',
    projectId: 'guesstimate-dev-478820',
    storageBucket: 'guesstimate-dev-478820.firebasestorage.app',
    androidClientId: '811437731406-a2shalhol9694hb8pm3859gb50n1tmm0.apps.googleusercontent.com',
    iosClientId: '811437731406-94h9o9u8u62djjerc7tsrf6ubf1nalvd.apps.googleusercontent.com',
    iosBundleId: 'com.guesstimate.fermiFrontend',
  );

}